### PR TITLE
ybs factory

### PR DESCRIPTION
**Pull request by wavey0x**

### CODE REVIEW

**Comment by dudesahn** [comment]
tests look good, contracts look good

a nit, but more generally, maybe add a bit more natspec. Contract titles, function notice, etc. 

specifically, missing info for the `_rewardToken` param here: https://github.com/yearn/yearn-boosted-staker/blob/8e57cc8a5bb9cd4abaf1327042783fac23d27995/contracts/factory/YBSRegistry.sol#L76

**Comment by dudesahn** [comment]
another nit, but might be nice to index these fields for the `NewDeployment` event

https://github.com/yearn/yearn-boosted-staker/blob/8e57cc8a5bb9cd4abaf1327042783fac23d27995/contracts/factory/YBSRegistry.sol#L23

**Comment by dudesahn** [comment]
might make sense to automatically add `_owner` as an `approvedDeployer` here, but not necessarily needed since you could just make sure to include the owner address in the array on deployment. do we anticipate having any `approvedDeployers`. Or were you thinking yChad would be owner and 4A would be an approved deployer?

https://github.com/yearn/yearn-boosted-staker/blob/8e57cc8a5bb9cd4abaf1327042783fac23d27995/contracts/factory/YBSRegistry.sol#L55

**Comment by wavey0x** [comment]
> might make sense to automatically add `_owner` as an `approvedDeployer` here, but not necessarily needed since you could just make sure to include the owner address in the array on deployment. do we anticipate having any `approvedDeployers`. Or were you thinking yChad would be owner and 4A would be an approved deployer?
> 
> https://github.com/yearn/yearn-boosted-staker/blob/8e57cc8a5bb9cd4abaf1327042783fac23d27995/contracts/factory/YBSRegistry.sol#L55

exactly, ychad = owner and 4A = approved deployer.

as far as deployer checks, i think owner should be distinct and always-approved. this way, if it ever changes (e.g. veYFI), we only need to update in one place `transferOwnership`, while still guaranteeing that owner always has deploy permissions.

https://github.com/yearn/yearn-boosted-staker/blob/8e57cc8a5bb9cd4abaf1327042783fac23d27995/contracts/factory/YBSRegistry.sol#L152

**Pull request merged**
